# Generated by Django 4.0.1 on 2022-03-19 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='head_post',
            field=models.BooleanField(default=False),
        ),
    ]
